### ISSUE TITLE
How to jump to the done step ?

### ISSUE THREAD

**Issue by raphaelmsr** [ycs77/laravel-wizard#16]
Edit : I can redirect to /wizard/*/done and destroy all session data, is that enough ?
Edit2 : cant redirect :(

**Comment by ycs77** [comment]
Hi, you can use the following code:

*app/Http/Controllers/[your WizardController].php*
```php
// Clear wizard cache
$this->wizard()->cache()->clear();

// Redirect to done page
return redirect()->route('done');
```

**Comment by ycs77** [comment]
If you want save data can use this code:

*app/Http/Controllers/[your WizardController].php*
```php
if ($this->wizard()->option('cache')) {
    $data = $this->save($request);
}

return $this->doneRedirectTo($data);
```

**Comment by raphaelmsr** [comment]
Sorry for the late late reply, will have a look at this, thanks for your reactivity as always !

**Comment by raphaelmsr** [comment]
Im not sure how to implement it ? I want to implement it according to the values passed between the steps, so I need some logic in the app/Http/Controllers/Steps/[step controller].php somewhere in model() and then $this->redirectToDone($data);
How do I achieve that

**Comment by ycs77** [comment]
Can you provide step class example code?

**Comment by raphaelmsr** [comment]
What do you want to see ? I didnt code any logic yet
I have two Steps, according to a value in step1, I would like to bypass step 2 and go straight toi step2. Should i put the code in Model in the second step? This is the only place where i can picture it

**Comment by ycs77** [comment]
Sorry, I didn't fully understand you said just now. I understand now.

**Comment by ycs77** [comment]
For example:

```php
<?php

namespace App\Http\Controllers;

use App\Steps\User\EmailStep;
use App\Steps\User\NameStep;
use Illuminate\Http\Request;
use Ycs77\LaravelWizard\Step;
use Ycs77\LaravelWizard\Wizardable;

class UserWizardController extends Controller
{
    use Wizardable;

    /**
     * The wizard name.
     *
     * @var string
     */
    protected $wizardName = 'user';

    /**
     * The wizard title.
     *
     * @var string
     */
    protected $wizardTitle = 'User';

    /**
     * @var string
     */
    protected $param;

    /**
     * The wizard steps instance.
     *
     * @var array
     */
    protected $steps = [
        NameStep::class,
        EmailStep::class,
    ];

    /**
     * On wizard step saved event.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Ycs77\LaravelWizard\Step  $step
     * @return \Illuminate\Http\RedirectResponse|null
     */
    protected function wizardStepSaved(Request $request, Step $step)
    {
        if ($step instanceof NameStep && $step->data('name') === 'skip') {
            $data = null;

            if ($this->wizard()->option('cache')) {
                $data = $this->save($request);
            }

            return $this->redirectToDone($data);
        }
    }
}

```

**Comment by ycs77** [comment]
You can to `wizardStepSaved` method to add your logic.

**Comment by ycs77** [comment]
The above code is, if the currently process step is `NameStep`, and the `name` field input is "skip", the jump to the done page is performed.

**Comment by raphaelmsr** [comment]
Just perfect, this is so great. Lots of people using this package it seems !!!
