### ISSUE TITLE
Action App\Http\Controllers\store not defined after upgrade to 2.1.0

### ISSUE THREAD

**Issue by raphaelmsr** [ycs77/laravel-wizard#18]
Something seems to have bugged in Wizardable.php i guess

**Comment by raphaelmsr** [comment]
There was an issue even after publishing the views again
So i had to manually replace `action(` with `$getActionUrl(`
Now its working

**Comment by ycs77** [comment]
You can use **FORCE** publish views:

```
php artisan vendor:publish --tag=wizard-views --force
```
