### ISSUE TITLE
File upload in form makes Error :  Serialization of 'Illuminate\Http\UploadedFile' is not allowed 

### ISSUE THREAD

**Issue by raphaelmsr** [ycs77/laravel-wizard#21]
I saw in the doc to disable the cache; but isn't there a way to simply bypass it for Serialization and let the current step model take care of saving data just for this input ?

**Comment by mikev032** [comment]
Refer to the docs:
https://github.com/ycs77/laravel-wizard#common-problems

**Comment by ycs77** [comment]
> duplicate issue #9

This problem can't be solved completely now, only the alternative. [see solution](https://github.com/ycs77/laravel-wizard#common-problems). If you have a real solution, please let me know.

**Comment by ycs77** [comment]
I have thought of: save the file first and save the URL to the cache. When save data, move the file to the location you really want to save.

Then schedule the time to add it.

**Comment by peterkacinec** [comment]
hi, i have the same issue. is there a way how to inject service in step controller?

**Comment by ycs77** [comment]
@peterkacinec Hi, you can use `app()` (or `App::make()`) inject any service to step class. See Laravel docs: https://laravel.com/docs/8.x/container#the-make-method

If you have other issues, can open new issue to discuss 😄.

**Comment by ycs77** [comment]
Released [v2.3.3](https://github.com/ycs77/laravel-wizard/releases/tag/v2.3.3) to fixed this.
