### ISSUE TITLE
Hi, may I know how to add parameter behind the step url? ex: {domain}/wizard/user?param=param

### ISSUE THREAD

**Issue by chinyeep123** [ycs77/laravel-wizard#33]
**Use Version:**
Use version when bugs appear.
- Laravel: v8.0.0
- Laravel Wizard: v2.3.1

**Describe the bug**

**To Reproduce**
Provide some code here to reproduce the bug.

**Expected behavior**

**Additional context**

**Comment by ycs77** [comment]
Just added!

If you visit "{domain}/wizard/user?param=value", you can use the following methods to obtain param value in `SomeStep`'s `saveData` method (the step name is example):

*SomeStep.php*
```php
class SomeStep extends Step
{
    public function saveData(Request $request, $data = null, $model = null)
    {
        $param = $request->query('param'); // return "value"

        // // Save some data...
        // $data = Arr::only($data, 'name');
        // $model->update($data);
    }
}
```

**Comment by ycs77** [comment]
I closed this issue, if you have any problem, you can open a new issue.
