### ISSUE TITLE
Prefix Cache?

### ISSUE THREAD

**Issue by mjamilasfihani** [ycs77/laravel-wizard#42]
Any ideas how to set the cache as prefix? Maybe it's cool each Step's controller has their own prefix, sorry if I miss something..

**Comment by mjamilasfihani** [comment]
I am sorry, I mean in the Wizards\MyController the prefix should be :)

**Comment by ycs77** [comment]
Hi @mjamilasfihani, can you provide some example? And describe where exactly you want to use it?

**Comment by mjamilasfihani** [comment]
Thanks for your attention @ycs77 :)

I have a Team's feature in my application, and I use this wizard for filling some requirement. And they can change their default team, let's say `status_active` is run into default mode (`false`)

Than it will redirect into wizard automatically, there'll gonna be a problem : if in wizard mode with cache, than I fill it without saving into database. and in the middle of step I change to another team (with status is `false` too). it will bring the old cache, not for the new team.

Does it caused by same name of the cache? I thought yes.

**Comment by ycs77** [comment]
Hi @mjamilasfihani, you can follow these steps:

### Custom cache key

Create `app/Wizard/CacheManager.php` file to extends the `CacheManager` to custom session key:

```php
// app/Wizard/CacheManager.php
<?php

namespace App\Wizard;

use Illuminate\Support\Facades\Auth;
use Ycs77\LaravelWizard\Cache\CacheManager as BaseCacheManager;

class CacheManager extends BaseCacheManager
{
    protected function getSessionKey()
    {
        /** @var \App\Models\User */
        $user = Auth::user();

        if ($user && $user->status_active) {
            // "laravel_wizard.user_is_active"
            return 'laravel_wizard.'.$this->wizard->getName().'_is_active';
        }

        // "laravel_wizard.user"
        return 'laravel_wizard.'.$this->wizard->getName();
    }
}
```

And set the custom `CacheManager` class to my wizard controller:

```php
// app/Http/Controllers/UserWizardController.php
<?php

namespace App\Http\Controllers;

...
use App\Wizard\CacheManager;
use Ycs77\LaravelWizard\Wizardable;

class UserWizardController extends Controller
{
    use Wizardable {
        wizard as baseWizard;
    }

    ...

    protected function wizard()
    {
        if (! $this->wizard) {
            $this->wizard = $this->baseWizard();
            $this->wizard->setCache((new CacheManager(app(), $this->wizard))->driver());
        }

        return $this->wizard;
    }
}
```

Now, if you change `$user->status_active` to `true` or `false`, there will be different caches.

If has another problem you can open a new issue.
