### ISSUE TITLE
SaveData function issue

### ISSUE THREAD

**Issue by thakurdinesh2** [ycs77/laravel-wizard#43]
**Use Version:**
Use version when bugs appear.
- Laravel: v8.0.0
- Laravel Wizard: v2.3.1

**Describe the bug**
Try to call curl request and get some errors. Is there any way to stop on same step with errors ?

**To Reproduce**
Provide some code here to reproduce the bug.

**Expected behavior**

**Additional context**

**Comment by ycs77** [comment]
Hi @thakurdinesh2, you can follow the steps:

1. First you must disable the wizard `cache` option on your WizardController, and let the `saveData()` method called on after each step:

    ```php
    class UserWizardController extends Controller
    {
        use Wizardable;

        protected $wizardOptions = [
            'cache' => false,
        ];
    }
    ```

2. Throw the `ValidationException` when the CURL error throws in the Step class, then will show the error message under the `name` field:

    ```php
    class NameStep extends Step
    {
        public function saveData(Request $request, $data = null, $model = null)
        {
            throw ValidationException::withMessages([
                'name' => 'The CURL request has some error.',
            ]);
        }
    }
    ```

You can try it~
