### ISSUE TITLE
Can't use with Laravel Breeze

### ISSUE THREAD

**Issue by Lexian-droid** [ycs77/laravel-wizard#46]
Hello, I'm trying to use this package to create a setup wizard in Laravel 10, I am using php 8.1, and I'm unable to use this package because it expects layouts.app, trouble is, breeze uses that for it's dashboard, and I don't really know how to fix this, It gives an error saying that "slot" is not a valid variable.

Is there anything that can be done?

**Comment by ycs77** [comment]
Hi @Lexian-droid, I am not planned support Laravel Breeze. When I built this package, it was used with Laravel UI, but now I have no plans to be compatible with Laravel Breeze. It would help to search for other Wizard packages or write the Wizard yourself.
