### ISSUE TITLE
Change the layout of the blade steps

### ISSUE THREAD

**Issue by raphaelmsr** [ycs77/laravel-wizard#8]
Changed the @extends in base.blade.php in vendor but since it is not commited, it is not persistent in my code base. How to change global layout of steps ?

**Comment by ycs77** [comment]
First, publish layouts:

```bash
php artisan vendor:publish --tag=wizard-views
```

Now you can customize `resources/views/vendor/wizard/*.blade.php` in your laravel project.

But if you want custom only one wizard view base view, you can copy the views from `resources/views/vendor/wizard/*.blade.php` to `resources/views/wizards/user/*.blade.php`. (`user` is `wizardName` property value on your wizard controller),

**Comment by raphaelmsr** [comment]
Works like a charm
