### ISSUE TITLE
Serialization of 'Illuminate\Http\UploadedFile' is not allowed

### ISSUE THREAD

**Issue by onedios** [ycs77/laravel-wizard#9]
I have three tabs, last tab is used to store documents(images) Next button is working fine but Prev button gives me this error.

also Is it possible we skip some steps ?

**Comment by ycs77** [comment]
1. Do you want to skip the steps?
2. Can you provide detailed information and sample code?

**Comment by onedios** [comment]
1. Yes some kind of flag used in UserStep for example to skip that step in session
2. Sure

I have three tabs
First tab shows user information
Second tab his/her address
Third tab is used to save image for that user

I moved image part into third tab because Next and Back button gave me this error, Still i am getting same error on back button.

I changed some codes in vendor folder (temporary)

in Step.php cacheProgress
`if($this->slug !== 'documents') {
            $cacheData[$this->slug] = $this->getRequestData($request);
`}

Reason i am getting this error
In SessionStore.php Set method

$this->session->put($this->wizardKey, $data);

Rest of my codes are simple no validation no saving right now.

**Comment by ycs77** [comment]
Hi! Thank you for the information. Now, I found a solution to set `cache` in `config / wizard.php` to false, but it doesn't work now, please wait for me to fix this.

**Comment by ycs77** [comment]
But I can't solve the "Serialization of 'Illuminate\Http\UploadedFile' is not allowed" problem.

**Comment by ycs77** [comment]
Now that I created a branch that fixes a bug where the cache is set to false, change the version of ycs77/laravel-wizard to `dev-hotfix/no-cache` in composer.json and run `composer update ycs77/laravel-wizard` .

The difference between cache open and close is:
* When the cache is enabled, the data will only be stored in the database at the end, and the process data will be cached.
* When the cache is disabled, the data will be saved in the data immediately after each step is sent. If you are afraid to save the data repeatedly, you can hide the Prev button, or use `Model::updateOrCreate()` (https://laravel.com/docs/6.x/eloquent#other-creation-methods).

**Comment by ycs77** [comment]
About the skip step: The current practice, as long as there is no input data and the rules are not set to require can skip step, and show instructions below the form field. I am planning to find free time to implement the real skip feature.

**Comment by onedios** [comment]
Hi thanks for the quick response and update, another scenario when we go back we should skip validation also because it make no sense to validate first (my address tab has 10 fields) and go back so there must be some flag set to skip validation when back trigger fires!

**Comment by ycs77** [comment]
Fix it!!

Change the version of ycs77/laravel-wizard to dev-hotfix/cant-goback-validation in composer.json and run `composer update ycs77/laravel-wizard`. Changes: https://github.com/ycs77/laravel-wizard/pull/14/files. If the problem can be solved, I will merge this branch to the master branch.

**Comment by ycs77** [comment]
There are still questions to welcome to tell me. If no problems, I will release a new version.

**Comment by onedios** [comment]
I guess final question !

The way we add validation rules can we add error message method also?

**Comment by ycs77** [comment]
Added from #15

**Comment by ycs77** [comment]
Friendly reminder: One issue will only discuss one thing. if there are other things that need to open a new issue. This will not be confusing!

**Comment by ycs77** [comment]
If there are no problems, I prepared to release a new version! Thank you for all your questions!

**Comment by ycs77** [comment]
Release [v2.0.2](https://github.com/ycs77/laravel-wizard/releases/tag/v2.0.2)
If you have questions, you can open a new issue.
Thank you used Laravel Wizard! 😄
